[package]
name = "ostree-pin"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.ostree]
version = "0.16.0"
features = ["v2020_1"]

[dependencies]
gio = "0.15.12"
